module.exports = { 
    "to_rus" : {
        "имя": "first_name",
        "отчество" : "second_name",
        "фамилия" : "surname",
        "возраст" : "age",
        "дата.рождения" : "date_of_birth",
        "пол" : "gender",
        "смена" : "shift",
        "должность" : "position",
        "разряд" : "category",
        "квалификация" : "owns_equipment",
        "телефон" : "phone_number",
        "авто" : "auto",
        "дети" : "child",
        "больничный" : "is_ill",
        "отпуск": "is_vacation",

        "модель": "model",
        "момер": "state_car_number",
        "имена": "child_name",
        "начало": "date_ill_start",
        "конец": "date_ill_end",
        "дни": "days_vacation",
        "c": "date_of_vacation",
        "отсутствует": "is_absent"

    },
    "to_eng": {
        "first_name": "имя",
        "second_name" : "отчество",
        "surname" : "фамилия",
        "age" : "возраст",
        "date_of_birth" : "дата.рождения",
        "gender" : "пол",
        "shift" : "смена",
        "position" : "должность",
        "category" : "разряд",
        "owns_equipment" : "квалификация",
        "phone_number" : "телефон",
        "auto" : "авто",
        "child" : "дети",
        "is_ill" : "больничный",
        "is_vacation": "отпуск",
        "model": "модель",
        "state_car_number": "номер",
        "child_name": "имена",
        "date_ill_start": "начало",
        "date_ill_end": "конец",
        "days_vacation": "дни",
        "date_of_vacation": "c",
        "is_absent": "отсутствует"
    }
}

